variables:
  NAME: 'garminpay-java'
  VERACODE_APP_ID: '1760537'
  VERACODE_APP_NAME: 'ENG-GarminPayStash'

include:
  - project: 'garmin-boulder/boulder-tools/templates'
    file: 'composites/maven-library-pipeline.yml'
  - project: 'garmin-boulder/boulder-tools/templates'
    file: 'veracode.yml'

License Check:
  image: $JDK_IMAGE
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS -s $MAVEN_SETTINGS_XML license:check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
