image: $JDK_IMAGE

variables:
  ARTIFACT_PATH: target
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version'
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

cache:
  paths:
    - .m2/repository

stages:
  - lint
  - compile
  - test

Checkstyle Linting:
  stage: lint
  script:
    - echo "Running checkstyles and linting"
    - ./mvnw $MAVEN_CLI_OPTS checkstyle:check
  except:
    - main

Maven Clean Compile:
  stage: compile
  script:
    - echo "Compiling project"
    - ./mvnw $MAVEN_CLI_OPTS clean compile

Maven Test:
  stage: test
  script:
    - echo "Testing"
    - ./mvnw $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: $ARTIFACT_PATH/surefire-reports/*.xml
